# Default values for on-demand-micro-services-deployment-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # uncomment and fill registry name
  registry:  docker-registry.default.svc:5000
  name: default/helm-web-api
  tag: v1.0
  pullPolicy: Always

service:
  type: ClusterIP
  port: 4000

namespace: pase-system

# for the ingress functionallity - the ingress is the controller which exposes the newly deployed service
# Refer to the docs for more details
ingress:
  ingressNamespace: default
  minPort: 20000
  maxPort: 30000
  ingressLabel: ingress

# configuration for the rbac namespaces, service accounts, roles and binding names
rbac:
  helmServiceAccount: helm
  helmRole: tiller-user
  tillerServiceAccount: tiller
  tillerRoleBindingName: tiller-user-binding
  tillerNamespace: kube-system
env:
  helmPaseRepo: http://chartmuseum-chartmuseum.pase-system.svc:8080